### ISSUE TITLE
Improve "Ready to submit" notifications

### ISSUE THREAD

**Issue by jeremybettis** [sdefresne/gerrit-monitor#40]
I use the gerrit-monitor with chromium-review.googlesource.com

I would really like it if I got "Ready to submit" notifications even if the Verified label has no votes, since normally I will be the one adding that label, and it seems to get cleared frequently.

Likewise I would like to NOT get "ready to submit" notifications if the cl is already running in the commit queue.

Love the chrome extension.

**Comment by sdefresne** [comment]
This is probably caused by the Attention-Set feature of Gerrit.

The CQ bot changes the list of people in the Attention-Set when it is done running (or when it starts running sometime). It will add back the author. There are plans to improve how/when the CQ bot changes the Attention-Set, but they will probably never match 100% of how the people want to be notified (e.g. some people wants to be notified after each successful runs of the CQ, while others may only be interested by failures).

If you've configured the extension to use the Attention-Set (this is the default since a few releases), you may get notified when the CQ bot changes the Attention-Set. You can try to change the configuration of the extension to ignore the Attention-Set and instead check who made the last comment to the CL.

To do that, go into the extension configuration page and select "Disabled" for "Only use Attention Set to judge required attention" option.
